name: Run Capybara main.py script

on:
  schedule:
    # Run at 4:20pm (US Mountain Daylight Time) from March to October
    - cron: "20 22 * 3-10 *"
    # Run at 4:20pm (US Mountain Standard Time) from November to February
    - cron: "20 23 * 1-2,11-12 *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f python/requirements.txt ]; then pip install -r python/requirements.txt; fi

      - name: Run main.py
        env:
          BLUESKY_BOT_EMAIL: ${{ secrets.BLUESKY_BOT_EMAIL }}
          BLUESKY_BOT_PASSWORD: ${{ secrets.BLUESKY_BOT_PASSWORD }}
        run: python python/main.py
